version: '3.8'

services:
  caisse:
    build:
      context: .
    container_name: projet-caisse
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=magasin
      - DB_USER=magasin_user
      - DB_PASSWORD=secret
    volumes:
      - .:/app
    tty: true

  tests:
    build:
      context: .
    image: projet-caisse:nathanlamy
    command: pytest
    environment:
      - PYTHONPATH=/app
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=magasin
      - DB_USER=magasin_user
      - DB_PASSWORD=secret
    volumes:
      - .:/app
    working_dir: /app

  web:
    build:
      context: ./web
    container_name: web-flask
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=magasin
      - DB_USER=magasin_user
      - DB_PASSWORD=secret