version: '3.8'

services:
  tests:
    build:
      context: .
    image: projet-caisse:nathanlamy
    command: pytest
    environment:
      - PYTHONPATH=/app
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=magasin
      - DB_USER=magasin_user
      - DB_PASSWORD=secret
    volumes:
      - .:/app
    working_dir: /app

  db:
    image: postgres:14
    container_name: postgres-magasin
    environment:
      POSTGRES_DB: magasin
      POSTGRES_USER: magasin_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: