version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: magasin
      POSTGRES_USER: magasin_user
      POSTGRES_PASSWORD: secret

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    image: projet-caisse:nathanlamy
    command: pytest
    environment:
      - PYTHONPATH=/app
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=magasin
      - DB_USER=magasin_user
      - DB_PASSWORD=secret
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
