version: '3.8'

services:
  db-ci:
    image: postgres:14
    environment:
      POSTGRES_DB: magasin
      POSTGRES_USER: magasin_user
      POSTGRES_PASSWORD: secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U magasin_user"]
      interval: 5s
      timeout: 5s
      retries: 10

  tests-ci:
    build:
      context: .
      dockerfile: Dockerfile
    image: projet-caisse:nathanlamy
    command: sh -c "./wait-for-db.sh"
    environment:
      - PYTHONPATH=/app
      - DB_HOST=db-ci
      - DB_PORT=5432
      - DB_NAME=magasin
      - DB_USER=magasin_user
      - DB_PASSWORD=secret
    depends_on:
      db-ci:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
