version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres-magasin2
    environment:
      POSTGRES_DB: magasin
      POSTGRES_USER: magasin_user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  caisse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projet-caisse
    image: projet-caisse:nathanlamy
    environment:
      - PYTHONPATH=/app
      - DB_HOST=10.194.32.204 # IP de la VM
      - DB_PORT=5432
      - DB_NAME=magasin
      - DB_USER=magasin_user
      - DB_PASSWORD=secret
    volumes:
      - .:/app
    tty: true
    depends_on:
      - db

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    image: projet-caisse:nathanlamy
    container_name: tests
    command: pytest
    environment:
      - PYTHONPATH=/app
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=magasin
      - DB_USER=magasin_user
      - DB_PASSWORD=secret
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app

volumes:
  postgres_data:
