@startuml Gérer les retours (annuler une vente)
actor Console
participant Service
database "BD SQLite" as DB

Console -> Service : annuler_vente(id_vente)
Service -> DB : supprimer_vente(id_vente)
DB --> Service : confirmation
Service --> Console : confirmation
@enduml
