@startuml Vue_logique

class Produit {
  +id: int
  +nom: str
  +categorie: str
}

class Vente {
  +id: int
  +date: datetime
  +total: int
  +produits: List[Produit]
}

class produits_vendus {
  +vente_id: int
  +produit_id: int
}

Produit <-- produits_vendus
Vente <-- produits_vendus
Vente --> Produit : relation many-to-many

@enduml
