@startuml Vue_de_deploiement

node "Client Web (Docker)" {
  component "Flask Web App"
  component "SQLAlchemy"
}

node "Serveur PostgreSQL (Docker)" {
  database "PostgreSQL"
}

"Flask Web App" --> "PostgreSQL" : Connexion via TCP/IP (env DATABASE_URL)

@enduml
