@startuml Vue_de_deploiement

node "Client Console (VM Linux)" {
  component "Python + Rich + SQLAlchemy"
}

node "Serveur PostgreSQL (Docker)" {
  database "PostgreSQL"
}

"Python + Rich + SQLAlchemy" --> "PostgreSQL" : Connexion via TCP/IP (DATABASE_URL)

@enduml
