@startuml Vue_d_implementation

package "app" {
  package "presentation (web)" {
    class "web/app.py"
    class "web/templates/*.html"
  }

  package "persistance (accès BD)" {
    class "app/database/db.py"
  }
}

"web/app.py" --> "app/database/db.py" : accès aux données
"web/app.py" --> "web/templates/*.html" : rendu via Flask

@enduml
